export const DashboardTypes = {
    DASHBOARD: "DASHBOARD",
    LEVELS: "LEVELS",
    ADDLESSON: "ADDLESSON",
    USERS: "USERS",
    DOCUMENTS: "DOCUMENTS",
    VIDEOS: "VIDEOS",
    SETTINGS: "SETTINGS"
}